<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="DESKTOP-4OUNIVO" name="test.TestPlayer" tests="7" failures="1" timestamp="26 Apr 2018 18:32:16 GMT" time="0.111" errors="0">
  <testcase name="testGiveMoney" time="0.001" classname="test.TestPlayer"/>
  <testcase name="testSetPlayerPos" time="0.001" classname="test.TestPlayer"/>
  <testcase name="testTurnsLeftInJail" time="0.001" classname="test.TestPlayer"/>
  <testcase name="testSetTurnsLeftInJail" time="0.000" classname="test.TestPlayer"/>
  <testcase name="testMiscSettersAndGetters" time="0.000" classname="test.TestPlayer"/>
  <testcase name="testTakeMoney" time="0.106" classname="test.TestPlayer">
    <failure type="java.lang.AssertionError" message="Unexpected exception.">
      <![CDATA[java.lang.AssertionError: Unexpected exception.
at org.testng.Assert.fail(Assert.java:85)
at test.TestPlayer.testTakeMoney(Unknown Source)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:497)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.TestNG.privateMain(TestNG.java:1354)
at org.testng.TestNG.main(TestNG.java:1323)
Caused by: java.lang.NullPointerException
at core.Notification.notify(Unknown Source)
at core.Player.takeMoney(Unknown Source)
... 25 more
]]>
    </failure>
  </testcase> <!-- testTakeMoney -->
  <testcase name="testProperties" time="0.002" classname="test.TestPlayer"/>
</testsuite> <!-- test.TestPlayer -->
